name: Build macOS App

on:
  push:
    branches: [main] # adjust this if your main branch has a different name
  workflow_dispatch: # allows you to run the workflow manually from the Actions tab

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci

      - name: Install react-router-dom
        run: npm install react-router-dom

      - name: Build React app
        run: npm run build

      - name: Build Electron app
        run: npm run electron:build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: MacOS App
          path: dist/*.app

      - name: Build
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm run build

      - name: Clean npm cache and reinstall
        run: |
          npm cache clean --force
          rm -rf node_modules
          npm install

      - name: Install dmg-license
        run: npm install dmg-license --save-dev

      - name: Create scripts directory
        run: mkdir -p scripts

      - name: Create notarize.js
        run: |
          cat << EOF > scripts/notarize.js
          exports.default = async function notarizing(context) {
            return;
          };
          EOF

      - name: Check notarize.js content
        run: cat scripts/notarize.js

      - name: Install @babel/plugin-proposal-private-property-in-object
        run: npm install --save-dev @babel/plugin-proposal-private-property-in-object

      - name: Install dmg-license globally
        run: npm install -g dmg-license

      - name: Link dmg-license
        run: npm link dmg-license

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build

      - name: Build Electron app
        run: npm run electron:build

      - name: Update electron-builder
        run: npm install electron-builder@latest --save-dev
