name: Build macOS App

on:
  push:
    branches: [main] # adjust this if your main branch has a different name
  workflow_dispatch: # allows you to run the workflow manually from the Actions tab

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Install react-router-dom
        run: npm install react-router-dom

      - name: Build React app
        run: npm run build

      - name: Build Electron app
        run: npm run electron:build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: MacOS App
          path: dist/*.app

      - name: Build
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm run build
