name: Build
on: [push, pull_request]

jobs:
  build_on_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          node --version
          npm --version
          npm ci
      - name: Build React app
        run: npm run build
      - name: Build Electron app
        run: npm run package
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: mac-app
          path: dist/*.dmg