name: Build macOS App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          npm install
          npm install --save-dev electron electron-builder electron-is-dev

      - name: Build React app
        run: npm run build

      - name: Copy electron.js to build
        run: cp public/electron.js build/electron.js

      - name: Build Electron app
        run: npm run electron:build -- --publish never

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: MacOS App
          path: |
            dist/*.dmg
            dist/*.zip
