name: Build macOS App

on:
  push:
    branches: [ main ]  # adjust this if your main branch has a different name
  workflow_dispatch:    # allows you to run the workflow manually from the Actions tab

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # or whichever version you're using
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build React app
      run: npm run build
    
    - name: Build Electron app
      run: npm run electron:build
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: MacOS App
        path: dist/*.app